// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC81meWChlB_d70kP8rJSxiSMehH52kYBI',
    appId: '1:630538886855:web:bb93c97e9aca8501bba8e2',
    messagingSenderId: '630538886855',
    projectId: 'librarysearchapp',
    authDomain: 'librarysearchapp.firebaseapp.com',
    storageBucket: 'librarysearchapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvHBx7XwICpjtH2iBSVeSy7v-8H_rXIu0',
    appId: '1:630538886855:android:9e64b47d73684783bba8e2',
    messagingSenderId: '630538886855',
    projectId: 'librarysearchapp',
    storageBucket: 'librarysearchapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIVc5xxxNWabG0a92rPjZ0qp7SDs04wYw',
    appId: '1:630538886855:ios:9433152f4a7ac785bba8e2',
    messagingSenderId: '630538886855',
    projectId: 'librarysearchapp',
    storageBucket: 'librarysearchapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIVc5xxxNWabG0a92rPjZ0qp7SDs04wYw',
    appId: '1:630538886855:ios:9433152f4a7ac785bba8e2',
    messagingSenderId: '630538886855',
    projectId: 'librarysearchapp',
    storageBucket: 'librarysearchapp.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication8',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC81meWChlB_d70kP8rJSxiSMehH52kYBI',
    appId: '1:630538886855:web:86326c5d064a6de1bba8e2',
    messagingSenderId: '630538886855',
    projectId: 'librarysearchapp',
    authDomain: 'librarysearchapp.firebaseapp.com',
    storageBucket: 'librarysearchapp.firebasestorage.app',
  );
}
